local core = require("src.core")

hl.bind(core.mainMod .. " + RETURN", hl.dsp.exec_cmd(core.terminal))
hl.bind(core.mainMod .. " + Q", hl.dsp.window.close())
hl.bind(core.mainMod .. " + code:24", hl.dsp.window.close())
hl.bind("CTRL + SPACE", hl.dsp.exec_cmd("vicinae deeplink 'vicinae://launch/wm/switch-windows'"))
hl.bind(core.mainMod .. " + e", hl.dsp.exec_cmd(core.fileManager))
hl.bind(core.mainMod .. " + b", hl.dsp.exec_cmd(core.browser))
hl.bind(core.mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(core.mainMod .. " + F", hl.dsp.layout("colresize +conf"))
hl.bind(core.mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ action = "toggle" }))
hl.bind(core.mainMod .. " + SPACE", hl.dsp.exec_cmd(core.menu))
hl.bind(core.mainMod .. " + ALT + SPACE", hl.dsp.exec_cmd(core.clipboard))
hl.bind(core.mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(core.mainMod .. " + slash", hl.dsp.layout("promote"))
hl.bind(core.mainMod .. " + ESCAPE", hl.dsp.exec_cmd(core.powerMenu))
hl.bind(core.mainMod .. " + F12", hl.dsp.exec_cmd(core.lockScreen))
hl.bind(core.mainMod .. " + SHIFT + e", hl.dsp.exec_cmd("~/.local/bin/vim-anywhere"))

hl.bind("CTRL + SHIFT + 4", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))
hl.bind("CTRL + SHIFT + 3", hl.dsp.exec_cmd("hyprshot -m window --clipboard-only"))

hl.bind(core.mainMod .. " + CTRL + I", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call network togglePanel"))
hl.bind(core.mainMod .. " + CTRL + B", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call bluetooth togglePanel"))
hl.bind(core.mainMod .. " + C", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call plugin:clipper toggle"))
hl.bind(core.mainMod .. " + S", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call plugin:screen-toolkit toggle"))
hl.bind(core.mainMod .. " + CTRL + V", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call volume togglePanel"))

hl.bind(core.mainMod .. " + SHIFT + T", hl.dsp.group.toggle())
hl.bind(core.mainMod .. " + T", hl.dsp.group.next())

hl.bind(core.mainMod .. " + TAB", core.dispatch("movecurrentworkspacetomonitor r"))
hl.bind(core.mainMod .. " + SHIFT + TAB", core.dispatch("movecurrentworkspacetomonitor l"))

hl.bind(core.mainMod .. " + H", hl.dsp.layout("focus l"))
hl.bind(core.mainMod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(core.mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(core.mainMod .. " + L", hl.dsp.layout("focus r"))

hl.bind(core.mainMod .. " + SHIFT + H", hl.dsp.layout("swapcol l"))
hl.bind(core.mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }))
hl.bind(core.mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }))
hl.bind(core.mainMod .. " + SHIFT + L", hl.dsp.layout("swapcol r"))
hl.bind(core.mainMod .. " + minus", hl.dsp.layout("colresize -0.05"))
hl.bind(core.mainMod .. " + equal", hl.dsp.layout("colresize +0.05"))

-- Use physical top-row keycodes for workspace binds. Avoid printable-key parser/layout mismatch.
hl.bind(core.mainMod .. " + code:10", hl.dsp.focus({ workspace = 1 }))
hl.bind(core.mainMod .. " + code:11", hl.dsp.focus({ workspace = 2 }))
hl.bind(core.mainMod .. " + code:12", hl.dsp.focus({ workspace = 3 }))
hl.bind(core.mainMod .. " + code:13", hl.dsp.focus({ workspace = 4 }))
hl.bind(core.mainMod .. " + code:14", hl.dsp.focus({ workspace = 5 }))
hl.bind(core.mainMod .. " + code:15", hl.dsp.focus({ workspace = 6 }))
hl.bind(core.mainMod .. " + code:16", hl.dsp.focus({ workspace = 7 }))
hl.bind(core.mainMod .. " + code:17", hl.dsp.focus({ workspace = 8 }))
hl.bind(core.mainMod .. " + code:18", hl.dsp.focus({ workspace = 9 }))
hl.bind(core.mainMod .. " + code:19", hl.dsp.focus({ workspace = 10 }))

hl.bind(core.mainMod .. " + SHIFT + code:10", hl.dsp.window.move({ workspace = 1 }))
hl.bind(core.mainMod .. " + SHIFT + code:11", hl.dsp.window.move({ workspace = 2 }))
hl.bind(core.mainMod .. " + SHIFT + code:12", hl.dsp.window.move({ workspace = 3 }))
hl.bind(core.mainMod .. " + SHIFT + code:13", hl.dsp.window.move({ workspace = 4 }))
hl.bind(core.mainMod .. " + SHIFT + code:14", hl.dsp.window.move({ workspace = 5 }))
hl.bind(core.mainMod .. " + SHIFT + code:15", hl.dsp.window.move({ workspace = 6 }))
hl.bind(core.mainMod .. " + SHIFT + code:16", hl.dsp.window.move({ workspace = 7 }))
hl.bind(core.mainMod .. " + SHIFT + code:17", hl.dsp.window.move({ workspace = 8 }))
hl.bind(core.mainMod .. " + SHIFT + code:18", hl.dsp.window.move({ workspace = 9 }))
hl.bind(core.mainMod .. " + SHIFT + code:19", hl.dsp.window.move({ workspace = 10 }))

hl.bind(core.mainMod .. " + M", hl.dsp.focus({ workspace = "name:M" }))
hl.bind(core.mainMod .. " + N", hl.dsp.focus({ workspace = "name:N" }))
hl.bind(core.mainMod .. " + SHIFT + M", hl.dsp.window.move({ workspace = "name:M" }))
hl.bind(core.mainMod .. " + SHIFT + N", hl.dsp.window.move({ workspace = "name:N" }))

hl.bind(core.mainMod .. " + grave", hl.dsp.workspace.toggle_special("magic"))
hl.bind(core.mainMod .. " + SHIFT + grave", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(core.mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(core.mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(core.mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(core.mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.bind("CTRL + SUPER + mouse:274", core.keyword("cursor:zoom_factor 3.0"), { mouse = true })
hl.bind("CTRL + SUPER + mouse:274", core.keyword("cursor:zoom_factor 1.0"), { mouse = true, release = true })
