# tmux-sessionizer config
# TS_SEARCH_PATHS overrides the defaults (instead of adding to them)
# ~/dev:1 = only show first-level subfolders in dev (e.g., ~/dev/testdev)
TS_SEARCH_PATHS=(~/dev:1)

# TS_STATIC_PATHS = paths to include without scanning subdirectories
TS_STATIC_PATHS=(~)
